// Race / affiliation / identity / season JP -> EN labels, edited directly
// here -- Vite hot-reloads this file, no Python re-export needed. Mirrors
// (and supersedes, for these two fields) Data/localisation/Race.txt and
// Identity.txt+Genus.txt; python/aigis/localisation.py reads those same
// source files only to build unit/class/skill/ability names, which do need
// the wiki-crawl voting pipeline and can't move client-side the same way.

export const RACE_LABELS: Record<string, string> = {
  "なし": "None",
  "王国": "Kingdom",
  "白の帝国": "White Empire",
  "パルス王国": "Kingdom of Pars",
  "遠国": "Distant Land",
  "砂漠の国": "Desert Country",
  "〈七つの大罪〉": "Seven Deadly Sins",
  "異郷の騎士団": "Chivalric Order of the Foreign Land",
  "人間": "Human",
  "獣人": "Beastfolk",
  "竜人": "Dragonfolk",
  "エルフ": "Elf",
  "ダークエルフ": "Dark Elf",
  "ハーフエルフ": "Half-Elf",
  "ハーフダークエルフ": "Half Dark Elf",
  "ハーフデーモン": "Half-Demon",
  "半神": "Half-God",
  "天界人": "Celestial",
  "ドワーフ": "Dwarf",
  "ヴァンパイア": "Vampire",
  "デーモン": "Demon",
  "天使": "Angel",
  "妖怪": "Youkai",
  "仙人": "Hermit",
  "オーク": "Orc",
  "聖霊": "Spirit",
  "ねんどろいど": "Nendoroid",
  "ゴブリン": "Goblin",
  "アンデッド": "Undead",
  "プリンス": "Prince",
  "姫": "Princess",
  "東の国": "Eastern Country",
  "華の国": "Flower Country",
  "恋姫": "Koihime",
  "神": "God",
  "鳥人": "Birdfolk",
  "魚人": "Merfolk",
  "冥界人": "Underworld",
  "機械": "Machine",
  "サキュバス": "Succubus",
};

// identity attributes + seasonal genus tags, combined (matches aigis/
// localisation.py's tag_map = {**Identity, **Genus}).
export const TAG_LABELS: Record<string, string> = {
  "高貴": "Noble",
  "魔術師": "Magician",
  "魔界": "Makai",
  "飛行": "Flying",
  "重装": "Heavy",
  "聖職者": "Clergy",
  "弓兵": "Bowman",
  "機械": "Machine",
  "騎兵": "Cavalry",
  "銃士": "Gunner",
  "深海": "Deep Sea",
  "ドラゴン": "Dragon",
  "アンデッド": "Undead",
  "砲兵": "Artillery",
  "ジャイアント": "Giant",
  "仙人": "Hermit",
  "ちび": "Chibi",
  "英傑": "Hero",
  "サマー": "Summer",
  "学園": "School",
  "お正月": "New Year",
  "バレンタイン": "Valentine",
  "クリスマス": "Christmas",
  "ジューンブライド": "June Bride",
  "ハロウィン": "Halloween",
  "温泉": "Hot Spring",
  "エッグハント": "Egg Hunt",
};
